### ISSUE TITLE
Window creation

### ISSUE THREAD

**Issue by Ri0ee** [4math/Engine#16]
Need to create window using GLFW.

**Comment by OlegGedzjuns** [comment]
[Started writing](https://github.com/4math/Engine/commit/1d51b1acfd1c1ffae9bd62c0dd43ccae0845c68a)

**Comment by OlegGedzjuns** [comment]
[Added window creation using GLFW](https://github.com/4math/Engine/commit/d5343ee47ed8fec4b5dddf4537ab35304d4d67ca)
Added to merge queue

**Comment by OlegGedzjuns** [comment]
Merged, sent to testing

**Comment by OlegGedzjuns** [comment]
Tested, bugs fixed.
Request complite, issue can be closed
